import Image from "next/image";
import Link from "next/link";
import React from "react";
import repolight from "../public/repo-hero-light.svg";
import repodark from "../public/repo-hero-logo-dark.svg";
import circlelight from "../public/repo-hero-circles-light.svg";
import circledark from "../public/repo-hero-circles-dark.svg";
import { useTheme } from "next-themes";
import { BsArrowRightShort, BsArrowLeftShort } from "react-icons/bs";
import Head from "next/head";
import img from "../public/unsplash.jpg";
const RepoPage = () => {
  const { systemTheme, theme, setTheme } = useTheme();

  const renderThemeChanger = () => {
    const currentTheme = theme === "system" ? systemTheme : theme;

    if (currentTheme === "dark") {
      return (
        <div>
          {/* <Image
            src={circledark}
            alt="circle logo"
            className="absolute hidden lg:block lg:w-[28rem] top-0 left-[33.3%]"
          /> */}
          <Image
            src={repodark}
            alt="vercel logo"
            className="w-20 md:w-28 mx-auto"
          />
        </div>
      );
    } else {
      return (
        <div>
          <Image
            src={repolight}
            alt="vercel logo"
            className="w-20 md:w-28  mx-auto"
          />
        </div>
      );
    }
  };
  return (
    <>
      <Head>
        <title>TurboRepo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-40 px-4 md:px-0">
        <div className="border-b-2 border-gray-500 pb-2">
          {renderThemeChanger()}
          <h1 className="uppercase text-center text-xl md:text-3xl font-bold mb-4">
            Turborepo
          </h1>
          <h1 className="text-3xl md:text-6xl font-extrabold text-center dark:text-transparent text-black dark:bg-clip-text bg-gradient-to-tr dark:from-gray-400 dark:to-gray-50 ">
            The build system that
            <br /> makes ship happen
          </h1>
          <p className="text-center text-sm md:text-xl max-w-lg mx-auto  text-gray-500 dark:text-gray-300 mt-4">
            Turborepo is a high-performance build system for JavaScript and
            TypeScript codebases.
          </p>
          <div className="flex justify-center items-center gap-4 mt-8">
            <button className="bg-black dark:bg-white text-white dark:text-black font-bold rounded-md px-8 py-2 ">
              Get Started
            </button>
            <button className="px-12 py-2 border-[1px] dark:border-gray-500 border-gray-300 dark:hover:border-white hover:border-black rounded-md font-bold duration-500">
              GitHub
            </button>
          </div>
        </div>
        {/* banner */}
        <div className="text-center text-gray-400 mt-10 border-b-2 border-gray-500">
          <h1 className="text-5xl font-semibold">Work faster. Work better.</h1>
          <p className="text-sm md:text-lg max-w-lg mx-auto mt-3">
            Turborepo is a high-performance build system for JavaScript and
            TypeScript codebases.
          </p>
          <div className="flex flex-col sm:flex-row w-full mx-auto gap-4 justify-center mb-8 mt-8">
            <div class="mx-auto md:mx-0 w-[300px] bg-white rounded-lg shadow-2xl flex flex-col">
              <Image
                src={img}
                alt="Laptop on Desk"
                width={300}
                height={150}
                className="rounded-t-lg"
              />
              <div className="p-6">
                <h2 className="font-bold text-xl md:text-3xl mb-2 text-orange-700">
                  Horizontal Card
                </h2>
                <p className="text-orange-700">Look at me go sideways!</p>
              </div>
            </div>
            <div class="mx-auto md:mx-0 w-[300px] bg-white rounded-lg shadow-2xl flex flex-col">
              <Image
                src={img}
                alt="Laptop on Desk"
                width={300}
                height={150}
                className="rounded-t-lg"
              />
              <div className="p-6">
                <h2 className="font-bold text-xl md:text-3xl mb-2 text-orange-700">
                  Horizontal Card
                </h2>
                <p className="text-orange-700">Look at me go sideways!</p>
              </div>
            </div>
            <div class="mx-auto md:mx-0 w-[300px] bg-white rounded-lg shadow-2xl flex flex-col">
              <Image
                src={img}
                alt="Laptop on Desk"
                width={300}
                height={150}
                className="rounded-t-lg"
              />
              <div className="p-6">
                <h2 className="font-bold text-xl md:text-3xl mb-2 text-orange-700">
                  Horizontal Card
                </h2>
                <p className="text-orange-700">Look at me go sideways!</p>
              </div>
            </div>
          </div>
        </div>
        {/* banner */}
        <div className="md:px-20 text-gray-400 mt-10">
          <h1 className="text-3xl md:text-[5rem] font-semibold mb-4 md:mb-8">
            Start selling with Square.
          </h1>
          <div className="flex flex-col md:flex-row">
            <div className="flex flex-row items-center text-blue-700 w-[21rem]">
              <h1 className="text-xl md:text-3xl font-semibold">
                Start a free account
              </h1>
              <BsArrowRightShort className="text-3xl mt-2 hover:ml-2 duration-500" />
            </div>
            <div className="flex flex-row items-center text-blue-700 md:pl-">
              <h1 className="text-xl md:text-3xl font-semibold">
                Talk to our Sales team
              </h1>
              <BsArrowRightShort className="text-3xl mt-2 hover:ml-2 duration-500" />
            </div>
          </div>
          <h3 className="font-semibold text-2xl mb-2 mt-8">Stay in touch</h3>
          <p className="max-w-xl">
            Subscribe to our email list to receive advice from other business
            owners, support articles, tips from industry experts and more.
          </p>
          <div className="flex flex-col mt-4 w-full md:w-1/2">
            <input
              type="text"
              id="search-navbar"
              className="block w-full p-3 text-sm text-gray-900 border  rounded-lg dark:bg-gray-900/40 bg-gray-50 focus:ring-blue-500 dark:placeholder-gray-400 dark:text-white outline-none"
              placeholder="you@example.com"
            />
            <div className="my-4">
              <input id="checked" type="checkbox" />
              <label id="checked" className="ml-2">
                I would like to join Square’s email list to receive stories from
                business owners, industry tips, new product information and
                more.*
              </label>
            </div>
            <button className="bg-blue-600 hover:bg-blue-700 dark:text-black text-white rounded-md px-4 py-3">
              Sign Up Now
            </button>
          </div>
          <p className="text-gray-400 mt-4">
            Please refer to our *
            <Link href="#" className="text-blue-700">
              privacy policy
            </Link>{" "}
            for more details.
          </p>
        </div>
      </div>
    </>
  );
};

export default RepoPage;
